server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service
                fallbackUri: forward:/fallback/auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      auth-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5000
        permitted-number-of-calls-in-half-open-state: 3

jwt:
  secret:
    key: 32B099BB09034268456CFB32914092391ECB2B275F0FAB0E91740463EF8F424A25CA74134CF884DC1DE6B045EB71641D7DC08BBC23D9A7EC3E8D8439BAF04362
